# Generated by Django 3.1.7 on 2021-04-10 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='Record',
        ),
    ]
